app/api/open/get-image-by-id/route.ts, components/Masonry.tsx, components/MasonryItem.tsx, middleware.ts, package.json, pnpm-lock.yaml, server/lib/query.ts
=> feat: 新增照片直链

components/admin/upload/FileUpload.tsx
=> :bug: Fix image date exif parse error #83

components/BlurImage.tsx, components/admin/copyright/CopyrightList.tsx, components/admin/list/ListImage.tsx, components/admin/list/ListProps.tsx, components/admin/tag/DefaultTag.tsx, components/admin/tag/TagList.tsx, package.json, pnpm-lock.yaml, style/globals.css
=> fix: 调整预览图片渲染方式

components/MasonryItem.tsx
Fix [#42](https://github.com/besscroft/PicImpact/issues/42)
=> fix: 调整 exif 信息显示格式

components/MasonryItem.tsx
=> feat: support using directional keys to switch images

.gitignore, components/MasonryItem.tsx, components/admin/album/AlbumAddSheet.tsx, components/admin/album/AlbumEditSheet.tsx, prisma/migrations/20241129025605_v1_1/migration.sql, prisma/schema.prisma, server/db/operate.ts, server/db/query.ts, types/index.ts
Link #131 
允许以相册为范围设置 是否允许下载 (是否显示下载/复制 直链按钮) 同时提示版权归属, 在允许下载时，提示授权协议
由于对 prisma 是有点不大熟悉，不清楚是否所有地方修改到位
已经在 main branch 升级到该 分支测试过，应该问题不大
=> feat: 增加是否允许下载功能

components/login/UserFrom.tsx, server/actions.ts
=> fix: use more human friendly message for auth error

app/(default)/page.tsx, app/admin/settings/preferences/page.tsx, app/layout.tsx, app/providers/config-store-Providers.tsx, components/album/Masonry.tsx, components/album/MasonryItem.tsx, hono/settings.ts, hooks/useSWRInfiniteHook.ts, instrumentation.ts, messages/en.json, messages/ja.json, messages/zh-TW.json, messages/zh.json, server/db/operate.ts, stores/configStores.ts, types/index.ts
=> :bug: 修复精选模式下首页不显示复制和下载按钮问题。

prisma/migrations/20250226144408_add_json_field_indexes/migration.sql, prisma/schema.prisma
这里给 exif 这样的 json 字段添加了针对相机型号和镜头的特化索引
后续可以做的
1. About 页面列出当前用户有的相机
2. 相册根据型号过滤
=> feat: Add btree index for exif field

package.json
将 dev command 拆分为 dev:server 和 dev:prisma 这样在一些想在本地启动 local server 链接到已有数据库做测试的场景非常方便
=> chore: Split dev command into dev:server and dev:prisma

.gitignore, app/admin/settings/preferences/page.tsx, components/layout/Header.tsx, components/layout/HeaderLink.tsx, hono/settings.ts, instrumentation.ts, messages/en.json, messages/ja.json, messages/zh-TW.json, messages/zh.json, server/db/operate.ts, server/db/query.ts, types/index.ts
Implement new features for album display:
- Add custom album folding toggle
- Allow configuring number of albums to fold
- Update related components and translations
- Modify types and database queries to support new setting
=> feat: Add album folding configuration options

components/admin/upload/FileUpload.tsx
=> chore: remove custom file upload

components/admin/dashboard/CardList.tsx, components/animata/text/counter.tsx
=> fix: fix animation for camera counter

app/admin/about/page.tsx, components/animata/card/evervault-card.tsx, lib/github/get-contributors.ts
重新设计了关于页面，并且将卡片渲染的数据改为 api 请求获取。
=> refactor: update about page

hono/file.ts, server/lib/file-upload.ts, server/lib/s3api.ts
=> refactor: file upload module encapsulation

app/(default)/[...album]/page.tsx, app/(default)/label/[...tag]/page.tsx, app/(default)/page.tsx, app/admin/settings/preferences/page.tsx, components/admin/album/AlbumAddSheet.tsx, components/admin/album/AlbumEditSheet.tsx, components/album/Masonry.tsx, hono/settings.ts, instrumentation.ts, messages/en.json, messages/ja.json, messages/zh-TW.json, messages/zh.json, prisma/migrations/20250316134415_add_random_show_for_album/migration.sql, prisma/schema.prisma, server/db/operate.ts, server/db/query.ts, types/index.ts
- Introduced randomShow property in album schema and updated related database queries.
- Modified album fetching functions to include randomShow.
- Updated UI components to support random image sorting based on randomShow state.
- Enhanced album management sheets to allow toggling of randomShow setting.
=> feat: add randomShow functionality to albums

components/layout/admin/nav-main.tsx, components/layout/admin/nav-projects.tsx
=> fix: mobile menu router collapsible error

package.json, pnpm-lock.yaml
https://github.com/advisories/GHSA-f82v-jwr5-mffw
=> fix: Upgrade Next.js package version

app/(default)/[...album]/page.tsx, app/(default)/page.tsx, app/(default)/tag/[...tag]/page.tsx, components/admin/album/album-add-sheet.tsx, components/admin/album/album-edit-sheet.tsx, components/album/album-gallery.tsx, components/album/gallery.tsx, components/album/tag-gallery.tsx, prisma/migrations/20250418170241_update_show_default/migration.sql, prisma/schema.prisma, server/db/query/albums.ts, server/db/query/images.ts, types/props.ts
- 改进了客户端性能。
- 调整了默认值。
- 修复了部分问题。
=> :bug: random method

app/admin/about/page.tsx, components/admin/list/image-batch-delete-sheet.tsx, components/layout/admin/nav-user.tsx
=> fix: update style and version

app/admin/about/page.tsx, components/album/preview-image.tsx, components/icons/expand.tsx, package.json, pnpm-lock.yaml
=> :sparkles: lightbox and fullscreen

app/admin/list/page.tsx, components/admin/list/list-props.tsx, hooks/use-swr-infinite-server-hook.ts, hooks/use-swr-page-total-server-hook.ts, messages/en.json, messages/ja.json, messages/zh.json, server/db/query/images.ts, types/props.ts
=> feat: implement server-side fetching for image lists and total count by album with show status filter

components/admin/dashboard/card-list.tsx
=> feat: implement sortable table for camera statistics

app/admin/list/page.tsx, components/admin/list/list-props.tsx
=> fix: update showStatus handling in list component to support empty string and improve data fetching logic

components/admin/list/list-props.tsx, components/icons/circle-chevron-down.tsx
=> style: fix list options mobile style

hono/file.ts, hono/images.ts, lib/utils/file.ts
=> fix: direct upload not working

components/album/preview-image.tsx
=> fix : back to previous page when existing image preview

hono/download.ts, hono/file.ts, hono/settings.ts, instrumentation.ts, messages/en.json, messages/ja.json, messages/zh-TW.json, messages/zh.json, package.json, pnpm-lock.yaml, server/db/operate/configs.ts, server/lib/r2.ts, server/lib/s3.ts, server/lib/s3api.ts
- 合并了一些通用方法。
- 尝试修复预签名 url 的问题。 
- 更新了 cloudflare 的配置。
=> :bug: s3 api

app/admin/settings/preferences/page.tsx, components/admin/list/list-props.tsx, hono/settings.ts, instrumentation.ts, messages/en.json, messages/ja.json, messages/zh-TW.json, messages/zh.json, server/db/operate/configs.ts, server/db/query/configs.ts, server/db/query/images.ts
=> feat(settings): Add configuration options for maximum  admin images per page

components/admin/upload/livephoto-file-upload.tsx, components/admin/upload/multiple-file-upload.tsx, components/admin/upload/simple-file-upload.tsx, components/ui/file-upload.tsx
=> fix(file-upload): resolve file upload component's improper exception handling.

hono/images.ts
在新增图片数据时，对可能存在与 exif 中的时间进行验证，以避免数据库 TO_TIMESTAMP 在执行时抛出异常。
=> fix(upload): valid exif data_time
